### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by sollidy** [atls/apps#14]
### С чем связан запрос на фичу?

Обновление зависимостей в репозитории

### Расскажите как вы это себе видите

После обновления должны корректно отрабатывать следующие команды:
- yarn check
- yarn workspace @atls/grpc-playground-app dev
- yarn workspace @atls/grpc-playground-app build
- собственно сам проект должен запускаться на 3000 порту

### Приложите пример реализаций

- [Upgrade Interactive](https://classic.yarnpkg.com/lang/en/docs/cli/upgrade-interactive/)

**Comment by Nelfimov** [comment]
`react-ace` ошибку можно поправить сделав `Yarn patch` и поправив интерфейс.

Описание тут:
https://github.com/securingsincity/react-ace/issues/1547
