### ISSUE TITLE
Обновление зависимостей `@grpc-playground/editor-fragment`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/apps#15]
### С чем связан запрос на фичу?

Обновить пакеты в зависимостях

### Расскажите как вы это себе видите

Обновить зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by shifuwww** [comment]
> Обновить пакеты в зависимостях
Мне нужно обновить пакет **@grpc-playground/editor-fragment** ?
> Обновить зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды
Я должен просто написать команды которые надо использовать? Так как не указан репозиторий где нужно менять зависимости
`yarn  workspace <workspace> add @grpc-playground/editor-fragment@latest`
`yarn install`
`yarn check`
`yarn test unit`

**Comment by SlumberyDude** [comment]
@shifuwww Привет!

Тебе нужно обновить зависимости [вот в этом](https://github.com/atls/apps/tree/master/grpc-playground/fragments/editor-fragment) репозитории.

> Мне нужно обновить пакет @grpc-playground/editor-fragment ?

Да, это так

>Я должен просто написать команды которые надо использовать? Так как не указан репозиторий где нужно менять зависимости

Нет, нужно добиться обновления зависимостей. Для самого обновления рекомендую использовать `yarn  workspace <workspace> add ...` 

Команды `yarn check, yarn test unit` нужно чтобы проверить что все работает. Начни с того, что у тебя в репозитории еще до обновления все чеки проходят.

>yarn  workspace <workspace> add @grpc-playground/editor-fragment@latest

Это неправильно. `@grpc-playground/editor-fragment` это название твоего воркспейса, а пакеты, которые требуют обновления находятся в `package.json`.

**Comment by shifuwww** [comment]
@SlumberyDude  Понял) Спасибо

**Comment by shifuwww** [comment]
> Тебе нужно обновить зависимости [вот в этом](https://github.com/atls/apps/tree/master/grpc-playground/fragments/editor-fragment) репозитории.
>
`"react-ace": "patch:react-ace@npm%3A9.4.0#~/.yarn/patches/react-ace-npm-9.4.0-c0e2dac510.patch"`
Не понял как обновить эту зависимость, при обновлении через:
` yarn workspace @grpc-playground/editor-fragment add react-ace@latest` ставится версия 10.1.0 но без пути, из за этого не проходит typecheck (пробовал ставить 9.4.0 версию)

**Comment by SlumberyDude** [comment]
@shifuwww Привет. Тут у `react-ace` стоит пропатченная версия, думаю патч был вызван как раз тем, что не проходили тайпчеки. Необходимо установить более позднюю версию и пропатчить ее аналогичным образом, чтобы проходили тайпчеки. Про патчи в ярне можешь почитать [тут](https://itnext.io/patch-an-npm-dependency-with-yarn-ddde2e194576)

**Comment by shifuwww** [comment]
@SlumberyDude Есть ли правила именования веток? Можно ли назвать ветку:
`git branch enhancement:@grpc-playground/editor-fragment`?

**Comment by SlumberyDude** [comment]
@shifuwww Есть. Ветка должна начинаться с ключевого слова из конвенции. Доступные слова : `feat`, `fix`, `chore`, `test` , затем слеш и произвольное название. Например, `feat/update-dependency`

**Comment by shifuwww** [comment]
Все ли верно?
https://github.com/atls/apps/tree/feat/update-dependency

**Comment by SlumberyDude** [comment]
@shifuwww Ветку назвал верно, но в след. раз отражай как-то какую конкретно зависимость ты обновляешь в ее названии, потому что в одном репозитории может идти обновление сразу нескольких пакетов и тогда будет путаница.

Делай PR этой ветки в мастер. Ставь assign себя в этот PR и запрашивай у меня ревью, когда посчитаешь, что с таской все.
