### ISSUE TITLE
Обновление зависимостей `@grpc-playground/sidebar-fragment`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/apps#16]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by shifuwww** [comment]
` "@atls-ui-proto/layout": "0.0.7",` если поднять хоть на одну версию то при typecheck вылетает ошибка 
`.yarn/__virtual__/@atls-ui-parts-layout-virtual-cc8764b890/5/home/shifuwww/.yarn/berry/cache/@atls-ui-parts-layout-npm-0.0.8-67da601605-9.zip/node_modules/@atls-ui-parts/layout/dist/row/row.component.d.ts`
`  Error: Cannot find module 'react' or its corresponding type declarations.`
внтури workspace есть пакет `"react": "18.2.0",` а у `"@atls-ui-proto/layout"` нет зависимости react

**Comment by TorinAsakura** [comment]
> ` "@atls-ui-proto/layout": "0.0.7",` если поднять хоть на одну версию то при typecheck вылетает ошибка
> `.yarn/__virtual__/@atls-ui-parts-layout-virtual-cc8764b890/5/home/shifuwww/.yarn/berry/cache/@atls-ui-parts-layout-npm-0.0.8-67da601605-9.zip/node_modules/@atls-ui-parts/layout/dist/row/row.component.d.ts`
> ` Error: Cannot find module 'react' or its corresponding type declarations.`
> внтури workspace есть пакет `"react": "18.2.0",` а у `"@atls-ui-proto/layout"` нет зависимости react

- читай про yarn packageExtension
- смотри в .yarnrc.yml

**Comment by SlumberyDude** [comment]
@TorinAsakura Нам резолюшены в этой репе чистить? По идее они блокируют обновление зависимостей тем что фиксируют.

**Comment by TorinAsakura** [comment]
> @TorinAsakura Нам резолюшены в этой репе чистить? По идее они блокируют обновление зависимостей тем что фиксируют.

резолюшены нужны в качестве консолидирующих заплаток, если они не нужны - убирайте

**Comment by SlumberyDude** [comment]
@shifuwww По возможности постарайся пожалуйста почистить список `resolutions` в корневом `package.json`, то что ты уже обновил может внезапно поломаться потому что резолюшены фиксируют версии на уровне всего проекта и некоторые обновления могли быть по факту фиктивными и в дерево зависимостей не помещались.
