### ISSUE TITLE
Обновление зависимостей `data-registry` и `proto-registry`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/apps#19]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

В модулях в `grpc-playground/stores`

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by SlumberyDude** [comment]
@shifuwww Привет, как дела с таской?

**Comment by shifuwww** [comment]
> Привет, как дела с таской?
>
Оой сорян я про эту забыл оказывается, думал все уже
