### ISSUE TITLE
Обновление зависимостей `@atls/grpc-playground-app`

### ISSUE THREAD

**Issue by SlumberyDude** [atls/apps#20]
### С чем связан запрос на фичу?

Обновить версии пакетов в зависимостях

### Расскажите как вы это себе видите

Обновить версии зависимости до максимально возможных и зафиксировать таким образом, чтобы ничего не ломалось. Должны без ошибок проходить команды:

- `yarn install`
- `yarn check`
- `yarn test unit`

Если в пакете есть скрипты `build` и `prepack`, то они тоже должны проходить без ошибок.

### Исключения:
`typescript` обновлять не нужно.

### Приложите пример реализаций

https://classic.yarnpkg.com/lang/en/docs/cli/workspace/
`yarn workspace <workspace> add <package@1.2.3> <keys>`

**Comment by shifuwww** [comment]
@SlumberyDude Привет, это последний мой таск, нужно ли мне тегать после Андрея?

**Comment by SlumberyDude** [comment]
@shifuwww Привет, я у него запрашиваю ревью после того как сам посмотрю обычно. Если все в этой репе вычистим то посмотрим, думаю пока что не нужно

**Comment by shifuwww** [comment]
@SlumberyDude  Привет, немогу найти решение ошибки в `.yarn/__virtual__/next-virtual-b7c3883125/5/home/shifuwww/.yarn/berry/cache/next-npm-13.4.9-5c37513773-9.zip/node_modules/next/dist/server/base-http/node.d.ts`
ошибка : `Error: Type 'ServerResponse' is not generic.`

Можно узнать где можно про это почитать?

**Comment by SlumberyDude** [comment]
@shifuwww Привет, если хочешь найти конкретную причину ошибки, то я обычно смотрю в каком файле исходной либы (в данном случае next) возникает ошибка, нахожу его на гитхабе, смотрю его гит историю и иногда нахожу конкретный коммит, который меняет тип например. У некста вроде с 13.4  большие ломающие изменения пошли.

Вот тот файл, но дженериков я там не вижу
https://github.com/vercel/next.js/blob/canary/packages/next/src/server/base-http/node.ts

**Comment by shifuwww** [comment]
@SlumberyDude Ооо круто) Понял, спасибо

**Comment by Nelfimov** [comment]
Некст в наших проектах используем не выше 12.3.4

**Comment by SlumberyDude** [comment]
Закрыто в связи с мержем пулл реквеста
